# Generated by Django 3.1.2 on 2020-10-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='borrado',
            field=models.BooleanField(default=False),
        ),
    ]
